package view;

import dao.UsuarioDAO;
import javax.swing.JOptionPane;
import model.Usuario;
import java.sql.SQLException;
import java.util.List;

import javax.swing.JFormattedTextField;
import java.text.ParseException;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author LUISGUILHERMEDESOUZA
 */
public class Cadastro extends javax.swing.JFrame {

    /**
     * Creates new form Cadastro
     */
    public Cadastro() {
        setTitle("Tela de Cadastro");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cpfTxt = new javax.swing.JTextField();
        nomeTxt = new javax.swing.JTextField();
        sobrenomeTxt = new javax.swing.JTextField();
        cidadeTxt = new javax.swing.JTextField();
        emailTxt = new javax.swing.JTextField();
        btnAdicionar = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 200));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TELA DE CADASTRO");

        jLabel2.setText("NOME:");

        jLabel3.setText("SOBRENOME:");

        jLabel4.setText("E-MAIL:");

        jLabel5.setText("CIDADE:");

        jLabel6.setText("CPF:");

        cpfTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfTxtActionPerformed(evt);
            }
        });
        try{
            MaskFormatter mascararCpf = new MaskFormatter("###.###.###-##");
            mascararCpf.setPlaceholderCharacter('_');
            cpfTxt = new javax.swing.JFormattedTextField(mascararCpf);
        }catch(ParseException e){
            e.printStackTrace();
        }

        btnAdicionar.setBackground(new java.awt.Color(102, 102, 0));
        btnAdicionar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAdicionar.setText("ADICIONAR");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        btnAtualizar.setBackground(new java.awt.Color(51, 51, 255));
        btnAtualizar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAtualizar.setText("ATUALIZAR");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        btnDeletar.setBackground(new java.awt.Color(204, 0, 0));
        btnDeletar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDeletar.setText("DELETAR");
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NOME", "SOBRENOME", "E-MAIL", "CIDADE", "CPF"
            }
        ));
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cpfTxt)
                            .addComponent(emailTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                            .addComponent(sobrenomeTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                            .addComponent(cidadeTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                            .addComponent(nomeTxt))
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAdicionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAtualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDeletar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nomeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(sobrenomeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(emailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cidadeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdicionar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAtualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeletar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cpfTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private int IdUsuarioSelecionado = -1;

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        int linhaSelecionada = tabela.getSelectedRow();
        if (linhaSelecionada != -1) {
            IdUsuarioSelecionado = Integer.parseInt(tabela.getValueAt(linhaSelecionada, 0).toString());
            nomeTxt.setText(tabela.getValueAt(linhaSelecionada, 1).toString());
            sobrenomeTxt.setText(tabela.getValueAt(linhaSelecionada, 2).toString());
            emailTxt.setText(tabela.getValueAt(linhaSelecionada, 3).toString());
            cidadeTxt.setText(tabela.getValueAt(linhaSelecionada, 4).toString());
            cpfTxt.setText(tabela.getValueAt(linhaSelecionada, 5).toString());
        }
    }//GEN-LAST:event_tabelaMouseClicked

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        String addNome = nomeTxt.getText();
        String addSobrenome = sobrenomeTxt.getText();
        String addEmail = emailTxt.getText();
        String addCidade = cidadeTxt.getText();
        String addCpf = cpfTxt.getText();

        if (addNome.isEmpty() || addSobrenome.isEmpty() || addEmail.isEmpty() || addCidade.isEmpty() || addCpf.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor preencha todos os campos", "ERRO", JOptionPane.ERROR_MESSAGE);
        } else {
            Usuario novoUsuario = new Usuario(0, addNome, addSobrenome, addEmail, addCidade, addCpf);
            UsuarioDAO uDao;

            try {
                uDao = new UsuarioDAO();
                int res = uDao.InserirUsuario(novoUsuario);
                if (res == 1) {
                    JOptionPane.showMessageDialog(this, "Usuário criado com sucesso!", "SUCESSO", JOptionPane.INFORMATION_MESSAGE);
                    this.LimparFormulario();
                    CarregarDadosUsuario();
                } else {
                    JOptionPane.showMessageDialog(this, "Erro ocorrido ao inserir o usuário", "ERRO", JOptionPane.ERROR_MESSAGE);
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, e.getMessage(), "ERRO", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        String addNome = nomeTxt.getText();
        String addSobrenome = sobrenomeTxt.getText();
        String addEmail = emailTxt.getText();
        String addCidade = cidadeTxt.getText();
        String addCpf = cpfTxt.getText();

        if (addNome.isEmpty() || addSobrenome.isEmpty() || addEmail.isEmpty() || addCidade.isEmpty() || addCpf.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor preencha todos os campos", "ERRO", JOptionPane.ERROR_MESSAGE);
        } else {
            if (IdUsuarioSelecionado != -1) {
                Usuario AtualizarUsuario = new Usuario(IdUsuarioSelecionado, addNome, addSobrenome, addEmail, addCidade, addCpf);
                UsuarioDAO uDao;

                try {
                    uDao = new UsuarioDAO();
                    int res = uDao.updateUsuario(AtualizarUsuario);
                    if (res == 1) {
                        JOptionPane.showMessageDialog(this, "Usuário atualizado com sucesso!", "SUCESSO", JOptionPane.INFORMATION_MESSAGE);
                        this.LimparFormulario();
                        CarregarDadosUsuario();
                    } else {
                        JOptionPane.showMessageDialog(this, "Erro ao atualizar", "ERRO", JOptionPane.ERROR_MESSAGE);
                    }
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(this, e.getMessage(), "ERRO", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao atualizar", "ERRO", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        if(IdUsuarioSelecionado != -1){
            int confirmacao = JOptionPane.showConfirmDialog(this, "Você tem certeza que quer deletar esse usuário?",
                    "Confirme a ação",JOptionPane.YES_NO_CANCEL_OPTION);
            if(confirmacao == JOptionPane.YES_OPTION){
                UsuarioDAO uDao;
                try{
                    uDao = new UsuarioDAO();
                    uDao.deleteUsuario(IdUsuarioSelecionado);
                    JOptionPane.showMessageDialog(this,"Usuário deletado com sucesso!","Sucesso",JOptionPane.INFORMATION_MESSAGE);
                    this.LimparFormulario();
                    CarregarDadosUsuario();
                    IdUsuarioSelecionado = -1;
                }catch(SQLException e){
                    JOptionPane.showMessageDialog(this, "Erro ao deletar","ERRO",JOptionPane.ERROR_MESSAGE);
                }
            }
        }else{
            JOptionPane.showMessageDialog(this,"Nenhum usuário selecionado","ERRO",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void cpfTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfTxtActionPerformed
        String addNome = nomeTxt.getText();
        String addSobrenome = sobrenomeTxt.getText();
        String addEmail = emailTxt.getText();
        String addCidade = cidadeTxt.getText();
        String addCpf = cpfTxt.getText();
        //String cpf = cpfTxt.getText(); // <--- caso der conflito/erro, apagar essa linha
    }//GEN-LAST:event_cpfTxtActionPerformed

    private void LimparFormulario() {
        nomeTxt.setText("");
        sobrenomeTxt.setText("");
        emailTxt.setText("");
        cidadeTxt.setText("");
        cpfTxt.setText("");
    }

    private void CarregarDadosUsuario() throws SQLException {
        UsuarioDAO uDao = new UsuarioDAO();
        List<Usuario> usuarios = uDao.getUsuarios();
        String[][] dados = new String[usuarios.size()][6];

        for (int i = 0; i < usuarios.size(); i++) {
            dados[i][0] = String.valueOf(usuarios.get(i).getId());
            dados[i][1] = usuarios.get(i).getNome();
            dados[i][2] = usuarios.get(i).getSobrenome();
            dados[i][3] = usuarios.get(i).getEmail();
            dados[i][4] = usuarios.get(i).getCidade();
            dados[i][5] = usuarios.get(i).getCpf();
        }
        String[] nomeColuna = {"Id", "Nome", "Sobrenome", "Email", "Cidade", "Cpf"};
        tabela.setModel(new javax.swing.table.DefaultTableModel(dados, nomeColuna));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JTextField cidadeTxt;
    private javax.swing.JTextField cpfTxt;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nomeTxt;
    private javax.swing.JTextField sobrenomeTxt;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
